import textwrap

import pytest

from conan.test.utils.tools import TestClient


@pytest.mark.slow
@pytest.mark.tool("zig")
def test_zigdeps():
    """ A real ``zig build`` links a Conan static-library dependency (with 2 components,
    one requiring the other) through the glue generated by ZigDeps, and runs successfully """
    c = TestClient()
    liba_conanfile = textwrap.dedent("""
        import os
        from conan import ConanFile
        from conan.tools.files import copy

        class LibA(ConanFile):
            name = "liba"
            version = "1.0"
            package_type = "static-library"
            exports_sources = "comp1.c", "comp1.h", "comp2.c", "comp2.h"

            def build(self):
                self.run("zig cc -c comp1.c -o comp1.o")
                self.run("zig cc -c comp2.c -o comp2.o")
                self.run("zig ar rcs libcomp1.a comp1.o")
                self.run("zig ar rcs libcomp2.a comp2.o")

            def package(self):
                copy(self, "*.a", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.h", self.build_folder, os.path.join(self.package_folder, "include"))

            def package_info(self):
                self.cpp_info.components["comp1"].libs = ["comp1"]
                self.cpp_info.components["comp1"].requires = ["comp2"]
                self.cpp_info.components["comp2"].libs = ["comp2"]
        """)
    comp1_h = 'int comp1_value(void);\n'
    comp1_c = textwrap.dedent("""
        extern int comp2_value(void);
        int comp1_value(void) { return comp2_value() + 1; }
        """)
    comp2_h = 'int comp2_value(void);\n'
    comp2_c = 'int comp2_value(void) { return 41; }\n'

    app_conanfile = textwrap.dedent("""
        from conan import ConanFile

        class App(ConanFile):
            requires = "liba/1.0"
            generators = "ZigDeps"

            def build(self):
                self.run("zig build run")
        """)
    build_zig = textwrap.dedent("""
        const std = @import("std");
        const conan_setup = @import("conan_zig_deps/conan_setup.zig");

        pub fn build(b: *std.Build) void {
            const target = b.standardTargetOptions(.{});
            const optimize = b.standardOptimizeOption(.{});

            const mod = b.createModule(.{ .target = target, .optimize = optimize });
            mod.addCSourceFile(.{ .file = b.path("main.c"), .flags = &.{} });
            mod.link_libc = true;

            const exe = b.addExecutable(.{ .name = "app", .root_module = mod });
            conan_setup.linkDependencies(exe);
            b.installArtifact(exe);

            const run_cmd = b.addRunArtifact(exe);
            run_cmd.step.dependOn(b.getInstallStep());
            const run_step = b.step("run", "Run the app");
            run_step.dependOn(&run_cmd.step);
        }
        """)
    main_c = textwrap.dedent("""
        #include <stdio.h>
        extern int comp1_value(void);
        int main(void) {
            printf("comp1_value=%d\\n", comp1_value());
            return 0;
        }
        """)

    c.save({"liba/conanfile.py": liba_conanfile,
            "liba/comp1.h": comp1_h,
            "liba/comp1.c": comp1_c,
            "liba/comp2.h": comp2_h,
            "liba/comp2.c": comp2_c,
            "conanfile.py": app_conanfile,
            "build.zig": build_zig,
            "main.c": main_c})
    c.run("create liba")
    c.run("build .")
    assert "comp1_value=42" in c.out
